### PR TITLE
Added Favicon to the website

### LINKED ISSUE #21: Added the favicon to the website
- I added the favicon to your beautiful website. I believe is every website need a favicon, for enhanced the beauty of the website I read your repository that seem too attractive.
- Its main purpose is to help visitors locate your page easier when they have multiple tabs open.
-  I converted GDSC logo to favicon and then added to the repository.

### PR DESCRIPTION
**Pull request by dsrathore1**

### CODE REVIEW

**Comment by adityaoberai** [comment]
Hey @dsrathore1 
Could you please create an [issue](https://github.com/GDSC-Amity/Members-Showcase/issues) sharing the change you intend to create, why it is necessary and show what favicon you're adding?
If all that seems valid, I will assign the issue to you and will review your addition here.

**Comment by dsrathore1** [comment]
@adityaoberai OK

**Review by adityaoberai — CHANGES_REQUESTED** [review]
Please shift the favicon to a folder `Assets/Favicon`
After that, I will merge the same

**Comment by dsrathore1** [comment]
Added new folder into assets

**Review by adityaoberai — APPROVED** [review]

**Pull request merged**
