### PR TITLE
Update contribution instructions

### PR DESCRIPTION
**Pull request by adityaoberai**

### CODE REVIEW

**Comment by adityaoberai** [comment]
@agarwalraghav1687 @srivastavayushi @KhushiSharma22 please review the updated instructions

**Review by srivastavayushi — APPROVED** [review]

**Review by srivastavayushi — APPROVED** [review]
This is looking :sparkles:

**Review by KhushiSharma22 — APPROVED** [review]
Works good according to me!

**Review by agarwalraghav1687 — APPROVED** [review]
Looks Great

**Pull request merged**
